lRESCUETIME_API_KEY = RESCUETIME_API_KEY
TODOIST = {"email" : EMAIL, "password" : PASSWORD}
SPOTIFY = {"email" : EMAIL, 'client_id' : CLIENT_ID, 'client_secret': CLIENT_SECRET, 'redirect_uri': WHAT_YOU_ENTER_ON_SPOTIFY}
MOVES_KEYS = {'client_id':CLIENT_ID, 'client_secret':CLIENT_SECRET, 'redirect_uri': WHAT_YOU_ENTER_ON_MOVES}
WITHINGS_KEYS = {'API_KEY': API_KEY, 'API_SECRET' : API_SECRET}
TOGGL_API_TOKEN = TOGGL_API_TOKEN
STEPS_GOAL = STEP_GOAL
FOCUS_GOAL = FOCUS_GOAL
UNPRODUCTIVITY_GOAL = UNPRODUCTIVITY_GOAL
#Get the JSON share link from wakatime, similar to this (https://wakatime.com/share/@0c62f2ad-9fa5-43c7-a08f-7b1562918a7d/43cd4128-5361-43db-b51b-d965e3c575a5.json):
WAKATIME_CODING_TIME = JSON_LINK
WAKATIME_CODING_TYPE = JSON_LINK
MEDITATION_GOAL = 30
STEPS_GOAL = 5000
UNPRODUCTIVITY_GOAL = 1
INSIGHT_MEDITATION_LOGIN = {'username' : 'user', 'password' : 'pw'}
GOODREADS_INFO = {'user_id': '1', 'api_key' : '1'}
MEDIUM_USER = 'a'
