"""empty message

Revision ID: 51336f112ea1
Revises: 
Create Date: 2018-01-01 10:02:43.083439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51336f112ea1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates_completed_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_data_dictionary', sa.JSON(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_data')
    op.drop_table('dates_completed_goals')
    # ### end Alembic commands ###
