"""empty message

Revision ID: 8f4d5af9ffc5
Revises: fbd78b967e74
Create Date: 2017-11-05 14:52:09.922217

"""

# revision identifiers, used by Alembic.
revision = '8f4d5af9ffc5'
down_revision = 'fbd78b967e74'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_data', sa.Column('personal_data_dictionary', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('personal_data', 'steps')
    op.drop_column('personal_data', 'rescue_time_weekly')
    op.drop_column('personal_data', 'chess_rating')
    op.drop_column('personal_data', 'date')
    op.drop_column('personal_data', 'pomodoros')
    op.drop_column('personal_data', 'quote')
    op.drop_column('personal_data', 'rescue_time_daily')
    op.drop_column('personal_data', 'weight')
    op.drop_column('personal_data', 'steps_avg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_data', sa.Column('steps_avg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('personal_data', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('personal_data', sa.Column('rescue_time_daily', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('personal_data', sa.Column('quote', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('personal_data', sa.Column('pomodoros', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('personal_data', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('personal_data', sa.Column('chess_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('personal_data', sa.Column('rescue_time_weekly', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('personal_data', sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('personal_data', 'personal_data_dictionary')
    # ### end Alembic commands ###
