"""empty message

Revision ID: b71abed2fe24
Revises: None
Create Date: 2017-10-16 17:18:40.031643

"""

# revision identifiers, used by Alembic.
revision = 'b71abed2fe24'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rescue_time_daily', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('rescue_time_weekly', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('quote', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('chess_rating', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('steps_avg', sa.Integer(), nullable=True),
    sa.Column('pomodoros', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_data')
    # ### end Alembic commands ###
