"""empty message

Revision ID: fbd78b967e74
Revises: b71abed2fe24
Create Date: 2017-10-28 11:52:24.612224

"""

# revision identifiers, used by Alembic.
revision = 'fbd78b967e74'
down_revision = 'b71abed2fe24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates_completed_goals', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dates_completed_goals', 'id')
    # ### end Alembic commands ###
